### ISSUE TITLE
(Multi) Switch to permissive license? PyQT

### ISSUE THREAD

**Issue by SYZYGY-DEV333** [ajventer/pyKAN#10]
This code is licensed under GPL. This means any derivative HAS to have the same license no matter what. Also, any code that uses your code as a library has to use a GPL license. I was wondering if you could switch to an Apache or BSD-style license. Or possibly [this one](http://splicense.pen.io/).

Also: does it have to be PyQT or would Tkinter be acceptable? (I can write a Tkinter GUI fairly easily.)

**Comment by ajventer** [comment]
I prefer copyleft over permissive licenses. I do not want my code used in non-free projects. 

On the unrelated question of GUI library: you are free to write a TKInter GUI if you want to, but I think I'll still write a pyQT one as well :P I really want to learn pyQT and I love the look of QT apps - so I would like to do so. I'm not doing features until the beta branch is stable - and I'm waiting for at least a week after KSP1.2 to give people a chance to test against that. But in the meantime, master can gain features if other people have ideas.
There is no reason it could only have one gui - it was written as an abstract library-style program on purpose exactly so it could have multiple interfaces.

**Comment by SYZYGY-DEV333** [comment]
@ajventer 
Very well, this is your project; you can license it as you wish. I will not complain further. I might go ahead and get started on some sort of GUI using Tkinter, you or I or someone else can go back later and do something with QT.

Also: Not sure why I suddenly thought of this, but you might find [waffle.io](http://waffle.io) interesting. It's a simple issue/project management webapp where each issue shows up as a card, you can sort them into different categories. I have used it and have been happy with it.

**Comment by ajventer** [comment]
> I might go ahead and get started on some sort of GUI using Tkinter, 
> Feel free. I suggest taking the same approach I took - where pyKAN is teh commandline, there is an extant pyKANQT script (even if it doesn't do anything) where the QT GUI version should ultimately live. If you created a pyKANtk (or however you want to capitalise it) at the same level it will slot in neatly without breaking anything.
> Provided the code isn't too broken - I'll merge that in a heartbeat. I am in favour of giving users options.

**Comment by SYZYGY-DEV333** [comment]
@ajventer sounds good!
