### ISSUE TITLE
Exception on adding a directory

### ISSUE THREAD

**Issue by jforr** [ajventer/pyKAN#14]
See below for the command.  I'm not sure, but it could be related to the fact that I do not have my KSP installed in a default location.  When I run the code in PyKANSettings line by line I end up with a non-existent directory for steamKSPDir.

`PS E:\ksp\pyKAN-0.1.0> python .\pyKAN addkspdir --kspdir "E:\KSP\KSP_1.2.1\`
`python : Traceback (most recent call last)`
`At line:1 char:1`
`+ python .\pyKAN addkspdir --kspdir "E:\KSP\KSP_1.2.1\"`
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File ".\pyKAN", line 341, in <module>
    settings = pykancfg.PyKANSettings(kspdir)
  File "E:\ksp\pyKAN-0.1.0\libPyKAN\pykancfg.py", line 25, in __init__
    steamKSPDir = os.path.join(os.getenv('HOME'),'.local','share','Steam','steamapps','common','Kerbal Space Program')
  File "C:\Python34\lib\ntpath.py", line 108, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python34\lib\ntpath.py", line 159, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()`

**Comment by ajventer** [comment]
The latest commit on the master branch should fix this.
